config/routes.rb
Rails.application.routes.draw do
  resources :notes
  root to: "notes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:note_name, :note_entry)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuickNotes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "shared/header"%>
    <% if notice.present? %>
      <div class="alert alert-success" role="alert"><%= notice%></div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-danger" role="alert"><%= notice%></div>
    <% end %>
    <main class="container">
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>
      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field mb-3">
    <h5 class="mb-3 my-0 fw-normal"><%= form.label :note_name %></h5>
    <%= form.text_field :note_name %>
  </div>
  <div class="field mb-3">
    <h5 class="my-0 mb-3 fw-normal"><%= form.label :note_entry %></h5>
    <%= form.text_area :note_entry %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-outline-primary btn-sm"%>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h2>Editing Note</h2>
<div class="row row-cols-1 row-cols-md-3 mb-3">
      <div class="col">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
              <li><%= render 'form', note: @note %></li>
            </ul>
              <div class="mb-3">
                <%= link_to 'Cancel', notes_path, class: "btn btn-outline-primary btn-sm" %>
              </div>
          </div>
        </div>
      </div>
</div>

app/views/notes/index.html.erb
<div class="row row-cols-1 row-cols-md-3 mb-3">
    <% @notes.each do |note| %>
      <div class="col">
        <div class="card mb-4 shadow-sm">
          <div class="card-header">
            <h4 class="my-0 fw-normal text-center"><%= note.note_name %></h4>
          </div>
          <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
              <li><%= note.note_entry %></li>
            </ul>
              <div class="row row-cols-1 row-cols-md-5 mb-3">
                <p><%= link_to 'Edit', edit_note_path(note), class: "btn btn-outline-primary btn-sm" %></p>
                <%= button_to 'Delete', note, class: "btn btn-outline-primary btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
              <p class="font-italic">Created <%= time_ago_in_words(note.created_at) %> ago</p>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/notes/new.html.erb
<h2>New Note</h2>
<div class="row row-cols-1 row-cols-md-3 mb-3">
      <div class="col">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
              <li><%= render 'form', note: @note %></li>
            </ul>
              <div class="mb-3">
                <%= link_to 'Cancel', notes_path, class: "btn btn-outline-primary btn-sm" %>
              </div>
          </div>
        </div>
      </div>
</div>

app/views/notes/show.html.erb
<div class="row row-cols-1 row-cols-md-3 mb-3">
      <div class="col">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
              <h5 class="my-0 mb-2 fw-normal">Note name:</h5>
              <li><%= @note.note_name %></li>
              <h5 class="my-0 mb-2 fw-normal">Note entry:</h5>
              <li><%= @note.note_entry %></li>
            </ul>
              <div class="mb-3">
                <%= link_to 'Edit', edit_note_path(@note), class: "btn btn-outline-primary btn-sm" %>
              </div>
              <div class="mb-3">
                <%= link_to 'Back', notes_path, class: "btn btn-outline-primary btn-sm" %>
              </div>
          </div>
        </div>
      </div>
</div>

app/views/shared/_header.html.erb
<header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <p class="h5 my-0 me-md-auto fw-normal">QuickNotes
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-sticky" viewBox="0 0 16 16">
      <path d="M2.5 1A1.5 1.5 0 0 0 1 2.5v11A1.5 1.5 0 0 0 2.5 15h6.086a1.5 1.5 0 0 0 1.06-.44l4.915-4.914A1.5 1.5 0 0 0 15 8.586V2.5A1.5 1.5 0 0 0 13.5 1h-11zM2 2.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 .5.5V8H9.5A1.5 1.5 0 0 0 8 9.5V14H2.5a.5.5 0 0 1-.5-.5v-11zm7 11.293V9.5a.5.5 0 0 1 .5-.5h4.293L9 13.793z"/>
    </svg>
  </p>

  <nav class="my-2 my-md-0 me-md-3">
    <div>
      <%= link_to "Create new Note", new_note_path, class: "btn btn-outline-primary" %>
    </div>
  </nav>
</header>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="title">
      My Notes
  </h1>
  <p class="lead"></p>
</div>